[toolchain]
anchor_version = "0.31.1"

[features]
resolution = true
skip-lint = false

[programs.devnet]
invoice_claim = "7DCAzfvmrbjDuoQMSdamKwguDTQ48QAuedDHpWPynJvx"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "~/.config/solana/id.json"

[scripts]
bootstrap = "npx ts-node -P ./tsconfig.json scripts/bootstrap.ts"
debug-request-pda = "npx ts-node -P ./tsconfig.json scripts/debug_request_pda.ts"
init-payment-queue = "npx ts-node -P ./tsconfig.json scripts/init_payment_queue.ts"
request-vrf = "npx ts-node -P ./tsconfig.json scripts/request_vrf.ts"
submit = "npx ts-node -P ./tsconfig.json scripts/submit_request.ts"
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
test-invoice = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/invoice-flow-test.ts"
test-invoice-e2e = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/invoice-e2e-live-vrf.ts"
test-org = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/org-test.ts"
test-vendor = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/vendor-test.ts"
view-invoices = "npx ts-node -P ./tsconfig.json scripts/view_invoices.ts"
