[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
invoice_claim = "92icJAeAhsB1fPyoURiaC53pizWW5Kv7NU5X87WdRLBB"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "~/.config/solana/id.json"

[scripts]
bootstrap = "npx ts-node -P ./tsconfig.json scripts/bootstrap.ts"
request-vrf = "npx ts-node -P ./tsconfig.json scripts/request_vrf.ts"
submit = "npx ts-node -P ./tsconfig.json scripts/submit_request.ts"
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
test-invoice = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/invoice-test.ts"
test-org = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/org-test.ts"
test-vendor = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/vendor-test.ts"
